# Generated by Django 4.1 on 2022-08-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_info_blood_pressure_alter_info_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='pregnancies',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
