# Generated by Django 4.1 on 2022-08-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_info_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='location',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
