# Generated by Django 4.1 on 2022-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_info_result_alter_info_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='pregnancies',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
